export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  SUPPORT = 'SUPPORT',
  FINANCE = 'FINANCE',
  OPERATIONS = 'OPERATIONS',
  USER = 'USER',
}

export enum PointTransactionType {
  MEMBERSHIP_PURCHASE = 'MEMBERSHIP_PURCHASE',
  QUALIFYING_ACTIVITY = 'QUALIFYING_ACTIVITY',
  REWARD_REDEMPTION = 'REWARD_REDEMPTION',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
  BONUS_ACHIEVEMENT = 'BONUS_ACHIEVEMENT',
  REFERRAL_ACTIVITY_REWARD = 'REFERRAL_ACTIVITY_REWARD',
}

export enum PointStatus {
  COMPLETED = 'COMPLETED',
  PENDING = 'PENDING',
  REVERSED = 'REVERSED',
  EXPIRED = 'EXPIRED',
}

export enum PaymentStatus {
  CREATED = 'CREATED',
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum ClaimStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_VERIFICATION = 'UNDER_VERIFICATION',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DISBURSED = 'DISBURSED',
  CLOSED = 'CLOSED',
}

export enum SupportTicketStatus {
  OPEN = 'OPEN',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING = 'WAITING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum SupportTicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum KYCStatus {
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  KYC_VERIFIED = 'KYC_VERIFIED',
  KYC_REJECTED = 'KYC_REJECTED',
  RULE_MODIFIED = 'RULE_MODIFIED',
  MANUAL_POINT_ADJUSTMENT = 'MANUAL_POINT_ADJUSTMENT',
  MEMBERSHIP_PURCHASED = 'MEMBERSHIP_PURCHASED',
  CLAIM_STATUS_UPDATED = 'CLAIM_STATUS_UPDATED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  REWARD_DISPATCHED = 'REWARD_DISPATCHED',
  SYSTEM_CONFIG_UPDATED = 'SYSTEM_CONFIG_UPDATED',
}
