import bcrypt from 'bcryptjs';
import { UserRole, KYCStatus, PointTransactionType, PointStatus, SupportTicketStatus, SupportTicketPriority } from '../constants';

export interface InMemoryState {
  users: any[];
  nodes: any[];
  plans: any[];
  products: any[];
  benefits: any[];
  impactProjects: any[];
  rules: any[];
  ledger: any[];
  tickets: any[];
  claims: any[];
  redemptions: any[];
  auditLogs: any[];
  contactMessages: any[];
}

export const inMemoryStore: InMemoryState = {
  users: [],
  nodes: [],
  plans: [],
  products: [],
  benefits: [],
  impactProjects: [],
  rules: [],
  ledger: [],
  tickets: [],
  claims: [],
  redemptions: [],
  auditLogs: [],
  contactMessages: [],
};

export const initInMemoryStore = async () => {
  const passwordHash = await bcrypt.hash('Admin@Tridrishti2026', 10);
  const userPasswordHash = await bcrypt.hash('User@123456', 10);

  const superAdmin = {
    _id: 'user_admin_001',
    name: 'Tridrishti Platform Admin',
    email: 'admin@tridrishti.com',
    passwordHash,
    phone: '+91 9876543210',
    role: UserRole.SUPER_ADMIN,
    referralCode: 'TRI-ADMIN-001',
    level: 5,
    levelName: 'DIAMOND',
    pointsBalance: 50000,
    lifetimePointsEarned: 50000,
    lifetimePointsUsed: 0,
    kycStatus: KYCStatus.VERIFIED,
    isActive: true,
    isSuspended: false,
    createdAt: new Date().toISOString(),
  };

  const vedansh = {
    _id: 'user_vedansh_002',
    name: 'Vedansh Gupta',
    email: 'vedansh@tridrishti.com',
    passwordHash: userPasswordHash,
    phone: '+91 9988776655',
    role: UserRole.USER,
    referralCode: 'TRI-VDNSH-82K',
    referredBy: 'TRI-ADMIN-001',
    referrerUserId: superAdmin._id,
    level: 3,
    levelName: 'GROW',
    pointsBalance: 1250,
    pendingPoints: 100,
    lifetimePointsEarned: 2450,
    lifetimePointsUsed: 1200,
    kycStatus: KYCStatus.VERIFIED,
    kycDocuments: {
      panNumber: 'ABCDE1234F',
      aadhaarLast4: '8892',
      documentUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400',
      verifiedAt: new Date().toISOString(),
    },
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    address: {
      line1: 'Flat 402, Lotus Grand Residency',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201309',
      country: 'India',
    },
    isActive: true,
    isSuspended: false,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  };

  const rahul = {
    _id: 'user_rahul_003',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    passwordHash: userPasswordHash,
    phone: '+91 9811223344',
    role: UserRole.USER,
    referralCode: 'TRI-RAHUL-101',
    referredBy: 'TRI-VDNSH-82K',
    referrerUserId: vedansh._id,
    level: 2,
    levelName: 'CONNECT',
    pointsBalance: 650,
    lifetimePointsEarned: 950,
    lifetimePointsUsed: 300,
    kycStatus: KYCStatus.VERIFIED,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    isActive: true,
    isSuspended: false,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  };

  const priya = {
    _id: 'user_priya_004',
    name: 'Priya Patel',
    email: 'priya.patel@example.com',
    passwordHash: userPasswordHash,
    phone: '+91 9722334455',
    role: UserRole.USER,
    referralCode: 'TRI-PRIYA-202',
    referredBy: 'TRI-VDNSH-82K',
    referrerUserId: vedansh._id,
    level: 2,
    levelName: 'CONNECT',
    pointsBalance: 820,
    lifetimePointsEarned: 820,
    lifetimePointsUsed: 0,
    kycStatus: KYCStatus.PENDING,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    isActive: true,
    isSuspended: false,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  };

  const amit = {
    _id: 'user_amit_005',
    name: 'Amit Verma',
    email: 'amit.verma@example.com',
    passwordHash: userPasswordHash,
    phone: '+91 9633445566',
    role: UserRole.USER,
    referralCode: 'TRI-AMIT-303',
    referredBy: 'TRI-VDNSH-82K',
    referrerUserId: vedansh._id,
    level: 1,
    levelName: 'STARTER',
    pointsBalance: 150,
    lifetimePointsEarned: 150,
    lifetimePointsUsed: 0,
    kycStatus: KYCStatus.NOT_SUBMITTED,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    isActive: true,
    isSuspended: false,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  };

  inMemoryStore.users = [superAdmin, vedansh, rahul, priya, amit];

  inMemoryStore.plans = [
    {
      _id: 'plan_entry_100',
      name: 'TRIDRISHTI ENTRY ACTIVATION',
      code: 'TRI_ENTRY_100',
      price: 100,
      description: 'One-time ₹100 platform onboarding activation fee to unlock referral tools, start earning 10 TRI Coins per referral, and access community utilities.',
      triPointsReward: 10,
      features: [
        'Mandatory One-Time ₹100 Platform Activation',
        'Earn 10 Welcome TRI Coins credited instantly',
        'Generate Personal Referral Link to earn 10 Coins per referral',
        'Access to Level 1 Basic Healthcare Guidance',
        'Eligible for Welcome Goodie Pack & Community E-Book',
      ],
      goodiesIncluded: ['Tridrishti Welcome Kit Sticker', 'Community E-Handbook'],
      benefitsSummary: ['Telehealth Consultation Pass', 'Partner Insurance Assistance'],
      isActive: true,
      isFeatured: true,
      order: 1,
    },
    {
      _id: 'plan_pro_500',
      name: 'TRI PRO ADVANCED',
      code: 'TRI_PRO_500',
      price: 500,
      description: 'Accelerated membership tier with 60 TRI Coins bonus, Level 2 Fast-Track, and Priority Healthcare claims review.',
      triPointsReward: 60,
      features: [
        'Includes ₹100 Entry Activation',
        'Earn 60 Bonus TRI Coins',
        'Instant Level 2 Tier Progression',
        'Free Annual NABL Diagnostic Test Pass',
        'Higher Education Support Grant Eligibility',
      ],
      goodiesIncluded: ['Tridrishti Branded Stainless Steel Bottle', 'Welcome Pack'],
      benefitsSummary: ['Annual Full-Body Health Checkup', 'Education Grant Access'],
      isActive: true,
      isFeatured: false,
      order: 2,
    },
    {
      _id: 'plan_elite_1000',
      name: 'TRI ELITE AMBASSADOR',
      code: 'TRI_ELITE_1000',
      price: 1000,
      description: 'Highest leadership tier with 150 TRI Coins bonus, Level 3 instant unlocking, and local community drive sponsorship.',
      triPointsReward: 150,
      features: [
        'Includes All Starter & Pro Utilities',
        'Earn 150 Bonus TRI Coins',
        'Level 3 Instant Recognition',
        'VIP Concierge Helpdesk & Priority Insurance Underwriting',
        'Sponsor & Lead Local Social Welfare Drives',
      ],
      goodiesIncluded: ['Tridrishti Executive Embroidered Hoodie', 'VIP Gift Box'],
      benefitsSummary: ['Priority Medical Reimbursements', 'Comprehensive Tuition Scholarships'],
      isActive: true,
      isFeatured: false,
      order: 3,
    },
  ];

  inMemoryStore.products = [
    {
      _id: 'prod_hoodie',
      title: 'Tridrishti Signature Eco-Cotton Hoodie',
      description: 'Premium heavy-blend fleece hoodie made from 100% sustainably sourced organic cotton with custom Tridrishti embroidered crest.',
      category: 'Fashion',
      pointsRequired: 400,
      stock: 50,
      imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600',
      isActive: true,
      isFeatured: true,
      minLevelRequired: 1,
    },
    {
      _id: 'prod_watch',
      title: 'Noise Pulse Smartwatch & Health Tracker',
      description: '1.85-inch HD Display, SpO2 & 24/7 Heart Rate Monitor, 100+ Sports Modes, IP68 Water Resistant with 7-day battery life.',
      category: 'Electronics',
      pointsRequired: 950,
      stock: 25,
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
      isActive: true,
      isFeatured: true,
      minLevelRequired: 2,
    },
    {
      _id: 'prod_bottle',
      title: 'Smart Vacuum Insulated Temperature Bottle (750ml)',
      description: 'Double-walled stainless steel thermal flask with integrated touch LED temperature sensor display.',
      category: 'Lifestyle',
      pointsRequired: 250,
      stock: 120,
      imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600',
      isActive: true,
      isFeatured: false,
      minLevelRequired: 1,
    },
    {
      _id: 'prod_earbuds',
      title: 'boAt Airdopes True Wireless Earbuds',
      description: 'Signature bass, ENx noise-cancellation mic, Beast mode low latency, and up to 42 hours total playtime.',
      category: 'Electronics',
      pointsRequired: 800,
      stock: 40,
      imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
      isActive: true,
      isFeatured: true,
      minLevelRequired: 2,
    },
    {
      _id: 'prod_backpack',
      title: 'Ergonomic Urban Laptop Backpack (30L)',
      description: 'Water-repellent ballistic nylon backpack with padded 15.6" laptop compartment and USB charging port.',
      category: 'Accessories',
      pointsRequired: 650,
      stock: 30,
      imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600',
      isActive: true,
      isFeatured: false,
      minLevelRequired: 1,
    },
    {
      _id: 'prod_books',
      title: 'Best-Selling Leadership & Finance Book Set (5 Books)',
      description: 'Curated library including Atomic Habits, Psychology of Money, Deep Work, Mindset, and Start with Why.',
      category: 'Books',
      pointsRequired: 350,
      stock: 60,
      imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600',
      isActive: true,
      isFeatured: false,
      minLevelRequired: 1,
    },
    {
      _id: 'prod_kit',
      title: 'Comprehensive Home First-Aid & Wellness Medical Kit',
      description: 'Over 80 essential emergency medical supplies, digital thermometer, pulse oximeter, and certified emergency manual.',
      category: 'Healthcare',
      pointsRequired: 500,
      stock: 45,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600',
      isActive: true,
      isFeatured: false,
      minLevelRequired: 1,
    },
  ];

  inMemoryStore.benefits = [
    {
      _id: 'ben_telehealth',
      title: '24x7 Telehealth Doctor Consultation Pass',
      category: 'Healthcare',
      description: 'Unlimited access to certified general physicians and medical specialists through partner telehealth platform.',
      eligibility: 'Open to all active members with a valid membership.',
      minLevelRequired: 1,
      documentsRequired: ['Membership ID Card', 'Valid Govt Photo ID'],
      howToClaim: ['Navigate to Healthcare tab', 'Select Doctor Specialization', 'Instant Video/Audio consult link generated'],
      isActive: true,
      isFeatured: true,
      providerInfo: 'Delivered in partnership with ISO-certified Telehealth Networks.',
    },
    {
      _id: 'ben_checkup',
      title: 'Annual Preventative Diagnostics & Health Checkup',
      category: 'Healthcare',
      description: 'Complimentary full-body test package covering 60+ vital parameters (Liver, Kidney, Lipid profile, CBC, Blood Sugar).',
      eligibility: 'Members holding Level 2 (CONNECT) or higher.',
      minLevelRequired: 2,
      documentsRequired: ['Identity Proof', 'Level Confirmation Badge'],
      howToClaim: ['Book slot via dashboard', 'Phlebotomist collects home sample', 'Digital lab report in 24 hours'],
      isActive: true,
      isFeatured: true,
      providerInfo: 'Partnered with NABL & CAP Accredited Diagnostic Labs across India.',
    },
    {
      _id: 'ben_education',
      title: 'Tridrishti Higher Education Grant Support',
      category: 'Education',
      description: 'Direct financial scholarship grant for eligible children and members pursuing higher secondary, collegiate, or skill certifications.',
      eligibility: 'Members at Level 2 and above with proven academic enrollment.',
      minLevelRequired: 2,
      documentsRequired: ['College Fee Receipt / Admission Letter', 'Previous Marksheet', 'Income/Declaration Certificate'],
      howToClaim: ['Submit online grant application', 'Internal committee verification', 'Direct institutional disbursement'],
      isActive: true,
      isFeatured: true,
      providerInfo: 'Tridrishti Community Social Assistance Trust Fund.',
    },
  ];

  inMemoryStore.rules = [
    {
      _id: 'rule_entry_fee',
      key: 'ENTRY_FEE_AMOUNT',
      category: 'ONBOARDING_FEES',
      name: 'Mandatory First-Time Entry Fee (₹)',
      description: 'The mandatory one-time payment required for new members to activate their account and start earning referral coins.',
      value: 100,
      dataType: 'number',
    },
    {
      _id: 'rule_referral_payout',
      key: 'REFERRAL_REWARD_COINS',
      category: 'REWARD_POINTS',
      name: 'Referral Reward (TRI Coins)',
      description: 'Number of TRI Coins credited to sponsor upon a referred member completing their ₹100 entry activation.',
      value: 10,
      dataType: 'number',
    },
    {
      _id: 'rule_level_2',
      key: 'LEVEL_2_THRESHOLD',
      category: 'LEVEL_THRESHOLDS',
      name: 'Level 2 (CONNECT) Threshold',
      description: 'TRI Coins required to unlock Level 2 perks (Telehealth Pass & 5% Discount).',
      value: 50,
      dataType: 'number',
    },
    {
      _id: 'rule_level_3',
      key: 'LEVEL_3_THRESHOLD',
      category: 'LEVEL_THRESHOLDS',
      name: 'Level 3 (GROW) Threshold',
      description: 'TRI Coins required to unlock Level 3 perks (Full-Body Checkup Pass & Education Grant Eligibility).',
      value: 200,
      dataType: 'number',
    },
    {
      _id: 'rule_level_4',
      key: 'LEVEL_4_THRESHOLD',
      category: 'LEVEL_THRESHOLDS',
      name: 'Level 4 (LEAD) Threshold',
      description: 'TRI Coins required to unlock Level 4 perks (Comprehensive Tuition Scholarships & Priority Medical Claims).',
      value: 500,
      dataType: 'number',
    },
    {
      _id: 'rule_level_5',
      key: 'LEVEL_5_THRESHOLD',
      category: 'LEVEL_THRESHOLDS',
      name: 'Level 5 (DIAMOND) Threshold',
      description: 'TRI Coins required to unlock Level 5 perks (VIP Concierge & Social Impact Drive Sponsorship).',
      value: 1000,
      dataType: 'number',
    },
    {
      _id: 'rule_anti_fraud',
      key: 'ANTI_FRAUD_MAX_DAILY_REFERRALS',
      category: 'REFERRAL_LIMITS',
      name: 'Max Referrals Per 24h Window',
      description: 'Trigger suspicious velocity flag if an account registers more than this threshold in 24 hours.',
      value: 25,
      dataType: 'number',
    },
  ];

  inMemoryStore.ledger = [
    {
      _id: 'tx_001',
      transactionId: 'TXN-TRI-MEMBER-001',
      userId: vedansh._id,
      type: PointTransactionType.MEMBERSHIP_PURCHASE,
      amount: 600,
      balanceAfter: 600,
      source: 'MEMBERSHIP_PURCHASE',
      description: 'Eligible points for TRI PRO Membership purchase',
      status: PointStatus.COMPLETED,
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      _id: 'tx_002',
      transactionId: 'TXN-TRI-ACT-002',
      userId: vedansh._id,
      type: PointTransactionType.QUALIFYING_ACTIVITY,
      amount: 350,
      balanceAfter: 950,
      source: 'QUALIFYING_ACTIVITY',
      description: 'Participation in Social Impact Education Drive',
      status: PointStatus.COMPLETED,
      createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      _id: 'tx_003',
      transactionId: 'TXN-TRI-REF-003',
      userId: vedansh._id,
      type: PointTransactionType.REFERRAL_ACTIVITY_REWARD,
      amount: 1500,
      balanceAfter: 2450,
      source: 'REFERRAL_ACTIVITY',
      description: 'Community network engagement activity bonus',
      status: PointStatus.COMPLETED,
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      _id: 'tx_004',
      transactionId: 'TXN-TRI-RDM-004',
      userId: vedansh._id,
      type: PointTransactionType.REWARD_REDEMPTION,
      amount: -1200,
      balanceAfter: 1250,
      source: 'REWARD_STORE_REDEMPTION',
      description: 'Redemption for Noise Pulse Smartwatch & Hoodie',
      status: PointStatus.COMPLETED,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];

  inMemoryStore.contactMessages = [
    {
      _id: 'msg_001',
      name: 'Rohan Deshmukh',
      email: 'rohan.d@gmail.com',
      subject: 'Inquiry regarding TRI PRO Membership benefits',
      message: 'Hello Tridrishti team, I am interested in joining under the PRO membership. Could you clarify how the health checkup diagnostics voucher home sample collection works in Pune?',
      status: 'UNREAD',
      createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    },
    {
      _id: 'msg_002',
      name: 'Dr. Ananya Sharma',
      email: 'dr.ananya.s@healthcareplus.in',
      subject: 'Healthcare Partner Integration Proposal',
      message: 'Greetings. We run an NABL accredited laboratory network with 45 branches across North India and would like to explore offering priority diagnostics vouchers for your community members.',
      status: 'READ',
      createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    },
  ];

  console.log('[InMemoryStore] Initialized with demo users, products, rules, ledger, and contact inquiries.');
};
